/**
 * Voorbeeldinhoud: vier hoofdthema's met vervolgkeuzes en eindacties.
 *
 * Beeld: er wordt met opzet geen auteursrechtelijk materiaal meegeleverd.
 * Iedere tegel heeft een emoji als beeld en een eigen kleur; de begeleider
 * kan per tegel een eigen afbeelding en een eigen geluid uploaden.
 *
 * Geluid: de verwijzingen naar `assets/...` zijn bedoeld als plek voor eigen
 * opnames. Ontbreekt het bestand, dan slaat de app het geluid netjes over en
 * benoemt hij de keuze met de spraakmodule.
 */

import type { Scherm } from '../types';

/** Vaste kleuren met genoeg contrast tegen de donkere achtergrond. */
const KLEUR = {
  paars: '#7c3aed',
  roze: '#db2777',
  blauw: '#2563eb',
  groen: '#15803d',
  oranje: '#c2410c',
  turkoois: '#0f766e',
  geel: '#a16207',
  rood: '#b91c1c',
};

export const STANDAARD_SCHERMEN: Scherm[] = [
  {
    id: 'home',
    title: 'Wat wil je doen?',
    items: [
      {
        id: 'muziek',
        label: 'Muziek',
        emoji: '🎵',
        kleur: KLEUR.paars,
        action: { type: 'navigate', target: 'muziek-menu' },
      },
      {
        id: 'kapsalon',
        label: 'Kapsalon',
        emoji: '💇',
        kleur: KLEUR.roze,
        action: { type: 'navigate', target: 'kapsalon-menu' },
      },
      {
        id: 'shoppen',
        label: 'Shoppen en stijl',
        emoji: '👗',
        kleur: KLEUR.blauw,
        action: { type: 'navigate', target: 'shoppen-menu' },
      },
      {
        id: 'dieren',
        label: 'Dieren',
        emoji: '🐶',
        kleur: KLEUR.groen,
        action: { type: 'navigate', target: 'dieren-menu' },
      },
    ],
  },

  // --- Thema 1: Muziek ----------------------------------------------------
  {
    id: 'muziek-menu',
    title: 'Welke muziek wil je?',
    items: [
      {
        id: 'muziek-rustig',
        label: 'Rustig',
        emoji: '🌙',
        kleur: KLEUR.blauw,
        action: {
          type: 'audio',
          audio: 'assets/muziek-rustig.mp3',
          tekst: 'Rustige muziek',
          emoji: '🌙',
          kleur: KLEUR.blauw,
          duurMs: 8000,
        },
      },
      {
        id: 'muziek-vrolijk',
        label: 'Vrolijk',
        emoji: '☀️',
        kleur: KLEUR.geel,
        action: {
          type: 'audio',
          audio: 'assets/muziek-vrolijk.mp3',
          tekst: 'Vrolijke muziek',
          emoji: '☀️',
          kleur: KLEUR.geel,
          duurMs: 8000,
        },
      },
      {
        id: 'muziek-dansen',
        label: 'Dansen',
        emoji: '💃',
        kleur: KLEUR.roze,
        action: { type: 'navigate', target: 'muziek-dansen' },
      },
      {
        id: 'muziek-zelf',
        label: 'Zelf kiezen',
        emoji: '🎧',
        kleur: KLEUR.turkoois,
        action: { type: 'navigate', target: 'muziek-zelf' },
      },
    ],
  },
  {
    id: 'muziek-dansen',
    title: 'Dansen',
    items: [
      {
        id: 'dansen-confetti',
        label: 'Confetti',
        emoji: '🎉',
        kleur: KLEUR.roze,
        action: { type: 'confetti', kleur: KLEUR.roze, duurMs: 6000 },
      },
      {
        id: 'dansen-lichtjes',
        label: 'Lichtjes',
        emoji: '✨',
        kleur: KLEUR.paars,
        action: { type: 'colorSweep', kleur: KLEUR.paars, duurMs: 6000 },
      },
      {
        id: 'dansen-liedje',
        label: 'Dansliedje',
        emoji: '🕺',
        kleur: KLEUR.oranje,
        action: {
          type: 'audio',
          audio: 'assets/muziek-dansen.mp3',
          tekst: 'Dansliedje',
          emoji: '🕺',
          kleur: KLEUR.oranje,
          duurMs: 8000,
        },
      },
      {
        id: 'dansen-animatie',
        label: 'Bewegen',
        emoji: '🎈',
        kleur: KLEUR.turkoois,
        action: { type: 'animation', kleur: KLEUR.turkoois, emoji: '🎈', duurMs: 6000 },
      },
    ],
  },
  {
    id: 'muziek-zelf',
    title: 'Zelf kiezen',
    items: [
      {
        id: 'zelf-liedje-1',
        label: 'Liedje 1',
        emoji: '1️⃣',
        kleur: KLEUR.blauw,
        action: {
          type: 'audio',
          audio: 'assets/liedje-1.mp3',
          tekst: 'Liedje één',
          emoji: '🎵',
          kleur: KLEUR.blauw,
          duurMs: 8000,
        },
      },
      {
        id: 'zelf-liedje-2',
        label: 'Liedje 2',
        emoji: '2️⃣',
        kleur: KLEUR.groen,
        action: {
          type: 'audio',
          audio: 'assets/liedje-2.mp3',
          tekst: 'Liedje twee',
          emoji: '🎵',
          kleur: KLEUR.groen,
          duurMs: 8000,
        },
      },
      {
        id: 'zelf-liedje-3',
        label: 'Liedje 3',
        emoji: '3️⃣',
        kleur: KLEUR.oranje,
        action: {
          type: 'audio',
          audio: 'assets/liedje-3.mp3',
          tekst: 'Liedje drie',
          emoji: '🎵',
          kleur: KLEUR.oranje,
          duurMs: 8000,
        },
      },
      {
        id: 'zelf-boodschap',
        label: 'Mooi liedje!',
        emoji: '💬',
        kleur: KLEUR.paars,
        action: { type: 'speak', tekst: 'Wat een mooi liedje!', emoji: '💬', duurMs: 4000 },
      },
    ],
  },

  // --- Thema 2: Kapsalon --------------------------------------------------
  {
    id: 'kapsalon-menu',
    title: 'Wat doen we in de kapsalon?',
    items: [
      {
        id: 'kapsalon-kapsel',
        label: 'Kapsel kiezen',
        emoji: '✂️',
        kleur: KLEUR.roze,
        action: { type: 'navigate', target: 'kapsalon-kapsel' },
      },
      {
        id: 'kapsalon-kleur',
        label: 'Haarkleur kiezen',
        emoji: '🎨',
        kleur: KLEUR.paars,
        action: { type: 'navigate', target: 'kapsalon-kleur' },
      },
      {
        id: 'kapsalon-accessoires',
        label: 'Accessoires',
        emoji: '🎀',
        kleur: KLEUR.blauw,
        action: { type: 'navigate', target: 'kapsalon-accessoires' },
      },
      {
        id: 'kapsalon-geluiden',
        label: 'Kapsalongeluiden',
        emoji: '🔊',
        kleur: KLEUR.turkoois,
        action: { type: 'navigate', target: 'kapsalon-geluiden' },
      },
    ],
  },
  {
    id: 'kapsalon-kapsel',
    title: 'Welk kapsel?',
    items: [
      {
        id: 'kapsel-kort',
        label: 'Kort',
        emoji: '💁',
        kleur: KLEUR.blauw,
        action: { type: 'image', emoji: '💁', tekst: 'Kort haar', kleur: KLEUR.blauw, duurMs: 6000 },
      },
      {
        id: 'kapsel-lang',
        label: 'Lang',
        emoji: '👩',
        kleur: KLEUR.groen,
        action: { type: 'image', emoji: '👩', tekst: 'Lang haar', kleur: KLEUR.groen, duurMs: 6000 },
      },
      {
        id: 'kapsel-krullen',
        label: 'Krullen',
        emoji: '👩‍🦱',
        kleur: KLEUR.oranje,
        action: { type: 'image', emoji: '👩‍🦱', tekst: 'Krullen', kleur: KLEUR.oranje, duurMs: 6000 },
      },
      {
        id: 'kapsel-staart',
        label: 'Staart',
        emoji: '🧑‍🦰',
        kleur: KLEUR.roze,
        action: { type: 'image', emoji: '🧑‍🦰', tekst: 'Een staart', kleur: KLEUR.roze, duurMs: 6000 },
      },
    ],
  },
  {
    id: 'kapsalon-kleur',
    title: 'Welke haarkleur?',
    items: [
      {
        id: 'kleur-blond',
        label: 'Blond',
        emoji: '👱',
        kleur: KLEUR.geel,
        action: { type: 'colorSweep', kleur: '#eab308', tekst: 'Blond', duurMs: 6000 },
      },
      {
        id: 'kleur-bruin',
        label: 'Bruin',
        emoji: '👩‍🦰',
        kleur: '#78350f',
        action: { type: 'colorSweep', kleur: '#92400e', tekst: 'Bruin', duurMs: 6000 },
      },
      {
        id: 'kleur-roze',
        label: 'Roze',
        emoji: '🌸',
        kleur: KLEUR.roze,
        action: { type: 'colorSweep', kleur: '#ec4899', tekst: 'Roze', duurMs: 6000 },
      },
      {
        id: 'kleur-blauw',
        label: 'Blauw',
        emoji: '🦋',
        kleur: KLEUR.blauw,
        action: { type: 'colorSweep', kleur: '#3b82f6', tekst: 'Blauw', duurMs: 6000 },
      },
    ],
  },
  {
    id: 'kapsalon-accessoires',
    title: 'Welk accessoire?',
    items: [
      {
        id: 'accessoire-speld',
        label: 'Haarspeld',
        emoji: '📌',
        kleur: KLEUR.roze,
        action: { type: 'image', emoji: '📌', tekst: 'Een haarspeld', kleur: KLEUR.roze, duurMs: 6000 },
      },
      {
        id: 'accessoire-haarband',
        label: 'Haarband',
        emoji: '🎀',
        kleur: KLEUR.paars,
        action: { type: 'image', emoji: '🎀', tekst: 'Een haarband', kleur: KLEUR.paars, duurMs: 6000 },
      },
      {
        id: 'accessoire-bloem',
        label: 'Bloem',
        emoji: '🌺',
        kleur: KLEUR.rood,
        action: { type: 'image', emoji: '🌺', tekst: 'Een bloem', kleur: KLEUR.rood, duurMs: 6000 },
      },
      {
        id: 'accessoire-glitter',
        label: 'Glitter',
        emoji: '✨',
        kleur: KLEUR.turkoois,
        action: { type: 'confetti', kleur: KLEUR.turkoois, tekst: 'Glitter', duurMs: 6000 },
      },
    ],
  },
  {
    id: 'kapsalon-geluiden',
    title: 'Welk geluid?',
    items: [
      {
        id: 'geluid-haardroger',
        label: 'Haardroger',
        emoji: '💨',
        kleur: KLEUR.blauw,
        action: {
          type: 'audio',
          audio: 'assets/haardroger.mp3',
          tekst: 'De haardroger',
          emoji: '💨',
          kleur: KLEUR.blauw,
          duurMs: 6000,
        },
      },
      {
        id: 'geluid-schaar',
        label: 'Schaar',
        emoji: '✂️',
        kleur: KLEUR.groen,
        action: {
          type: 'audio',
          audio: 'assets/schaar.mp3',
          tekst: 'De schaar',
          emoji: '✂️',
          kleur: KLEUR.groen,
          duurMs: 6000,
        },
      },
      {
        id: 'geluid-water',
        label: 'Water',
        emoji: '🚿',
        kleur: KLEUR.turkoois,
        action: {
          type: 'audio',
          audio: 'assets/water.mp3',
          tekst: 'De waterstraal',
          emoji: '🚿',
          kleur: KLEUR.turkoois,
          duurMs: 6000,
        },
      },
      {
        id: 'geluid-klaar',
        label: 'Klaar!',
        emoji: '🪞',
        kleur: KLEUR.paars,
        action: { type: 'speak', tekst: 'Je haar is klaar!', emoji: '🪞', duurMs: 4000 },
      },
    ],
  },

  // --- Thema 3: Shoppen en stijl -----------------------------------------
  {
    id: 'shoppen-menu',
    title: 'Wat gaan we shoppen?',
    items: [
      {
        id: 'shoppen-kleding',
        label: 'Kleding',
        emoji: '👚',
        kleur: KLEUR.roze,
        action: { type: 'navigate', target: 'shoppen-kleding' },
      },
      {
        id: 'shoppen-schoenen',
        label: 'Schoenen',
        emoji: '👟',
        kleur: KLEUR.blauw,
        action: { type: 'navigate', target: 'shoppen-schoenen' },
      },
      {
        id: 'shoppen-tas',
        label: 'Tas',
        emoji: '👛',
        kleur: KLEUR.oranje,
        action: { type: 'navigate', target: 'shoppen-tas' },
      },
      {
        id: 'shoppen-sieraden',
        label: 'Sieraden',
        emoji: '💎',
        kleur: KLEUR.turkoois,
        action: { type: 'navigate', target: 'shoppen-sieraden' },
      },
    ],
  },
  {
    id: 'shoppen-kleding',
    title: 'Welke kleding?',
    items: [
      {
        id: 'kleding-jurk',
        label: 'Jurk',
        emoji: '👗',
        kleur: KLEUR.roze,
        action: { type: 'image', emoji: '👗', tekst: 'Een jurk', kleur: KLEUR.roze, duurMs: 6000 },
      },
      {
        id: 'kleding-trui',
        label: 'Trui',
        emoji: '🧥',
        kleur: KLEUR.blauw,
        action: { type: 'image', emoji: '🧥', tekst: 'Een trui', kleur: KLEUR.blauw, duurMs: 6000 },
      },
      {
        id: 'kleding-broek',
        label: 'Broek',
        emoji: '👖',
        kleur: KLEUR.turkoois,
        action: { type: 'image', emoji: '👖', tekst: 'Een broek', kleur: KLEUR.turkoois, duurMs: 6000 },
      },
      {
        id: 'kleding-shirt',
        label: 'Shirt',
        emoji: '👕',
        kleur: KLEUR.groen,
        action: { type: 'image', emoji: '👕', tekst: 'Een shirt', kleur: KLEUR.groen, duurMs: 6000 },
      },
    ],
  },
  {
    id: 'shoppen-schoenen',
    title: 'Welke schoenen?',
    items: [
      {
        id: 'schoenen-sneakers',
        label: 'Sneakers',
        emoji: '👟',
        kleur: KLEUR.blauw,
        action: { type: 'image', emoji: '👟', tekst: 'Sneakers', kleur: KLEUR.blauw, duurMs: 6000 },
      },
      {
        id: 'schoenen-laarzen',
        label: 'Laarzen',
        emoji: '👢',
        kleur: KLEUR.oranje,
        action: { type: 'image', emoji: '👢', tekst: 'Laarzen', kleur: KLEUR.oranje, duurMs: 6000 },
      },
      {
        id: 'schoenen-slippers',
        label: 'Slippers',
        emoji: '🩴',
        kleur: KLEUR.turkoois,
        action: { type: 'image', emoji: '🩴', tekst: 'Slippers', kleur: KLEUR.turkoois, duurMs: 6000 },
      },
      {
        id: 'schoenen-feest',
        label: 'Feestschoenen',
        emoji: '👠',
        kleur: KLEUR.roze,
        action: { type: 'confetti', kleur: KLEUR.roze, tekst: 'Feestschoenen', duurMs: 6000 },
      },
    ],
  },
  {
    id: 'shoppen-tas',
    title: 'Welke tas?',
    items: [
      {
        id: 'tas-schouder',
        label: 'Schoudertas',
        emoji: '👜',
        kleur: KLEUR.roze,
        action: { type: 'image', emoji: '👜', tekst: 'Een schoudertas', kleur: KLEUR.roze, duurMs: 6000 },
      },
      {
        id: 'tas-rugzak',
        label: 'Rugzak',
        emoji: '🎒',
        kleur: KLEUR.groen,
        action: { type: 'image', emoji: '🎒', tekst: 'Een rugzak', kleur: KLEUR.groen, duurMs: 6000 },
      },
      {
        id: 'tas-heuptas',
        label: 'Heuptas',
        emoji: '👝',
        kleur: KLEUR.oranje,
        action: { type: 'image', emoji: '👝', tekst: 'Een heuptas', kleur: KLEUR.oranje, duurMs: 6000 },
      },
      {
        id: 'tas-koffer',
        label: 'Koffer',
        emoji: '🧳',
        kleur: KLEUR.blauw,
        action: { type: 'image', emoji: '🧳', tekst: 'Een koffer', kleur: KLEUR.blauw, duurMs: 6000 },
      },
    ],
  },
  {
    id: 'shoppen-sieraden',
    title: 'Welke sieraden?',
    items: [
      {
        id: 'sieraad-ketting',
        label: 'Ketting',
        emoji: '📿',
        kleur: KLEUR.paars,
        action: { type: 'image', emoji: '📿', tekst: 'Een ketting', kleur: KLEUR.paars, duurMs: 6000 },
      },
      {
        id: 'sieraad-oorbellen',
        label: 'Oorbellen',
        emoji: '💠',
        kleur: KLEUR.turkoois,
        action: { type: 'image', emoji: '💠', tekst: 'Oorbellen', kleur: KLEUR.turkoois, duurMs: 6000 },
      },
      {
        id: 'sieraad-armband',
        label: 'Armband',
        emoji: '⌚',
        kleur: KLEUR.blauw,
        action: { type: 'image', emoji: '⌚', tekst: 'Een armband', kleur: KLEUR.blauw, duurMs: 6000 },
      },
      {
        id: 'sieraad-diamant',
        label: 'Glitterdiamant',
        emoji: '💎',
        kleur: KLEUR.roze,
        action: { type: 'confetti', kleur: '#22d3ee', tekst: 'Een glitterdiamant', duurMs: 6000 },
      },
    ],
  },

  // --- Thema 4: Dieren ----------------------------------------------------
  {
    id: 'dieren-menu',
    title: 'Welke dieren wil je zien?',
    items: [
      {
        id: 'dieren-huis',
        label: 'Huisdieren',
        emoji: '🐱',
        kleur: KLEUR.oranje,
        action: { type: 'navigate', target: 'dieren-huis' },
      },
      {
        id: 'dieren-boerderij',
        label: 'Boerderijdieren',
        emoji: '🐄',
        kleur: KLEUR.groen,
        action: { type: 'navigate', target: 'dieren-boerderij' },
      },
      {
        id: 'dieren-wild',
        label: 'Wilde dieren',
        emoji: '🦁',
        kleur: KLEUR.geel,
        action: { type: 'navigate', target: 'dieren-wild' },
      },
      {
        id: 'dieren-grappig',
        label: 'Grappige dieren',
        emoji: '🐒',
        kleur: KLEUR.paars,
        action: { type: 'navigate', target: 'dieren-grappig' },
      },
    ],
  },
  {
    id: 'dieren-huis',
    title: 'Welk huisdier?',
    items: [
      {
        id: 'huis-hond',
        label: 'Hond',
        emoji: '🐶',
        kleur: KLEUR.oranje,
        action: {
          type: 'animalSound',
          audio: 'assets/hond.mp3',
          emoji: '🐶',
          tekst: 'De hond blaft: woef woef!',
          kleur: KLEUR.oranje,
          duurMs: 6000,
        },
      },
      {
        id: 'huis-kat',
        label: 'Kat',
        emoji: '🐱',
        kleur: KLEUR.geel,
        action: {
          type: 'animalSound',
          audio: 'assets/kat.mp3',
          emoji: '🐱',
          tekst: 'De kat miauwt: miauw!',
          kleur: KLEUR.geel,
          duurMs: 6000,
        },
      },
      {
        id: 'huis-cavia',
        label: 'Cavia',
        emoji: '🐹',
        kleur: KLEUR.roze,
        action: {
          type: 'animalSound',
          audio: 'assets/cavia.mp3',
          emoji: '🐹',
          tekst: 'De cavia piept.',
          kleur: KLEUR.roze,
          duurMs: 6000,
        },
      },
      {
        id: 'huis-vis',
        label: 'Vis',
        emoji: '🐠',
        kleur: KLEUR.blauw,
        action: {
          type: 'animalSound',
          audio: 'assets/vis.mp3',
          emoji: '🐠',
          tekst: 'De vis zwemt stil rond.',
          kleur: KLEUR.blauw,
          duurMs: 6000,
        },
      },
    ],
  },
  {
    id: 'dieren-boerderij',
    title: 'Welk boerderijdier?',
    items: [
      {
        id: 'boerderij-koe',
        label: 'Koe',
        emoji: '🐄',
        kleur: KLEUR.groen,
        action: {
          type: 'animalSound',
          audio: 'assets/koe.mp3',
          emoji: '🐄',
          tekst: 'De koe loeit: boeh!',
          kleur: KLEUR.groen,
          duurMs: 6000,
        },
      },
      {
        id: 'boerderij-schaap',
        label: 'Schaap',
        emoji: '🐑',
        kleur: KLEUR.turkoois,
        action: {
          type: 'animalSound',
          audio: 'assets/schaap.mp3',
          emoji: '🐑',
          tekst: 'Het schaap blaat: bèèè!',
          kleur: KLEUR.turkoois,
          duurMs: 6000,
        },
      },
      {
        id: 'boerderij-paard',
        label: 'Paard',
        emoji: '🐴',
        kleur: KLEUR.oranje,
        action: {
          type: 'animalSound',
          audio: 'assets/paard.mp3',
          emoji: '🐴',
          tekst: 'Het paard hinnikt.',
          kleur: KLEUR.oranje,
          duurMs: 6000,
        },
      },
      {
        id: 'boerderij-kip',
        label: 'Kip',
        emoji: '🐔',
        kleur: KLEUR.geel,
        action: {
          type: 'animalSound',
          audio: 'assets/kip.mp3',
          emoji: '🐔',
          tekst: 'De kip tokt: tok tok!',
          kleur: KLEUR.geel,
          duurMs: 6000,
        },
      },
    ],
  },
  {
    id: 'dieren-wild',
    title: 'Welk wild dier?',
    items: [
      {
        id: 'wild-leeuw',
        label: 'Leeuw',
        emoji: '🦁',
        kleur: KLEUR.geel,
        action: {
          type: 'animalSound',
          audio: 'assets/leeuw.mp3',
          emoji: '🦁',
          tekst: 'De leeuw brult!',
          kleur: KLEUR.geel,
          duurMs: 6000,
        },
      },
      {
        id: 'wild-olifant',
        label: 'Olifant',
        emoji: '🐘',
        kleur: KLEUR.turkoois,
        action: {
          type: 'animalSound',
          audio: 'assets/olifant.mp3',
          emoji: '🐘',
          tekst: 'De olifant toetert!',
          kleur: KLEUR.turkoois,
          duurMs: 6000,
        },
      },
      {
        id: 'wild-aap',
        label: 'Aap',
        emoji: '🐵',
        kleur: KLEUR.oranje,
        action: {
          type: 'animalSound',
          audio: 'assets/aap.mp3',
          emoji: '🐵',
          tekst: 'De aap roept: oe oe aa aa!',
          kleur: KLEUR.oranje,
          duurMs: 6000,
        },
      },
      {
        id: 'wild-pinguin',
        label: 'Pinguïn',
        emoji: '🐧',
        kleur: KLEUR.blauw,
        action: {
          type: 'animalSound',
          audio: 'assets/pinguin.mp3',
          emoji: '🐧',
          tekst: 'De pinguïn waggelt voorbij.',
          kleur: KLEUR.blauw,
          duurMs: 6000,
        },
      },
    ],
  },
  {
    id: 'dieren-grappig',
    title: 'Grappige dieren',
    items: [
      {
        id: 'grappig-dansende-aap',
        label: 'Dansende aap',
        emoji: '🐒',
        kleur: KLEUR.paars,
        action: { type: 'animation', emoji: '🐒', kleur: KLEUR.paars, tekst: 'De aap danst!', duurMs: 6000 },
      },
      {
        id: 'grappig-eend',
        label: 'Rare eend',
        emoji: '🦆',
        kleur: KLEUR.groen,
        action: { type: 'animation', emoji: '🦆', kleur: KLEUR.groen, tekst: 'Een rare eend!', duurMs: 6000 },
      },
      {
        id: 'grappig-feest',
        label: 'Dierenfeest',
        emoji: '🎊',
        kleur: KLEUR.roze,
        action: { type: 'confetti', emoji: '🐾', kleur: KLEUR.roze, tekst: 'Dierenfeest!', duurMs: 6000 },
      },
      {
        id: 'grappig-boodschap',
        label: 'Wat grappig!',
        emoji: '💬',
        kleur: KLEUR.blauw,
        action: { type: 'speak', tekst: 'Wat een grappig dier!', emoji: '💬', duurMs: 4000 },
      },
    ],
  },
];
